#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the service package to those expected by
        # OpenMediaVault.
        if [ -z "${2}" ]; then
            systemctl stop teamspeak3.service
            systemctl disable teamspeak3.service
        fi

        SERVICE_XPATH_NAME="teamspeak3"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if [ ! -d /opt/teamspeak3 ] && getent passwd ts3 >/dev/null 2>&1; then
            userdel -r ts3 >/dev/null
        fi

        if ! getent passwd ts3 >/dev/null 2>&1; then
            adduser --quiet \
                    --system \
                    --ingroup nogroup \
                    --no-create-home \
                    --disabled-password \
                    --gecos "" \
                    ts3
        fi

        unzip /usr/share/ts3wi.zip -d /usr/share  && rm -f /usr/share/ts3wi.zip
        chown -R www-data:www-data /usr/share/ts3wi
        find /usr/share/ts3wi \( -type f -exec chmod 644 {} \; \) , \( -type d -exec chmod 755 {} \; \)
        chmod -R 777 /usr/share/ts3wi/{temp,templates_c,icons}
        chmod -R 777 /usr/share/ts3wi/site/backups

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "password" ""
            omv_config_add_element "${SERVICE_XPATH}" "queryport" "10011"
            omv_config_add_element "${SERVICE_XPATH}" "vsport" "9987"
            omv_config_add_element "${SERVICE_XPATH}" "fileport" "30033"
            omv_config_add_element "${SERVICE_XPATH}" "update" "0"
            omv_config_add_element "${SERVICE_XPATH}" "restartmsg" ""
            omv_config_add_element "${SERVICE_XPATH}" "eula" "0"
            omv_config_add_element "${SERVICE_XPATH}" "enablewi" "0"
            omv_config_add_element "${SERVICE_XPATH}" "languagewi" "en"
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
